### ISSUE TITLE
Get Window Titles fails with a unicode encode error for certain titles.

### ISSUE THREAD

**Issue by deepakaravind** [robotframework/SeleniumLibrary#1252]
# Prerequisites
Had a chat in the slack channel and the team suggested to create an issue

# For issues
## Steps to reproduce the issue
    Click Element    ${PrintButton}
    Sleep    ${TinyWait}
    select window by index  1
    close chrome print preview dialog
    Wait Until Keyword Succeeds    5 x    2 s    Select Window
    [Teardown]    Run Keywords    Select Window    main

## Error messages and additional information
*UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)*     
DEBUG    Traceback (most recent call last):
 File "c:\venv\lib\site-packages\SeleniumLibrary\__init__.py", line 360, in run_keyword
   return DynamicCore.run_keyword(self, name, args, kwargs)
 File "c:\venv\lib\site-packages\SeleniumLibrary\base\robotlibcore.py", line 102, in run_keyword
   return self.keywords[name](*args, **kwargs)
 File "c:\venv\lib\site-packages\SeleniumLibrary\keywords\window.py", line 142, in get_window_titles
   return self._log_list(titles)
 File "c:\venv\lib\site-packages\SeleniumLibrary\keywords\window.py", line 219, in _log_list
   msg.append('{}: {}'.format(index + 1, item))

## Expected behavior and actual behavior
As in Selenium2Library we should be able to retrieve all the window titles
Get Window Titles are :     @{openWindows} = [ undefined | Some Text John, Doe    DOB: xxxxxxx (xxy) Male   returnText: 3333 | returntext1    Doe, John    DOB: xxxxxx (21y) Male   returnText2:  33333333 ]

## Environment

Browser: Chrome, Driver : chromedriver: 2.38, PYthon: 2.7, SeleniumLibrary:3.1.1, 
Operating System: Name and version (Linux, Ubuntu 18.04)

**Comment by aaltat** [comment]
I can see where the bug is, I need to make test for it and fix it.

**Comment by deepakaravind** [comment]
Thanks for looking into this bug.  I do see it is tagged to v3.3.0, could you give me an idea as to when would it be released?

**Comment by aaltat** [comment]
This is part of the 3.3.0 release. Timeline is always hard to give, because this project runs on (like many other open source projects) people free time and good will.

**Comment by deepakaravind** [comment]
Alrighty no problem thanks for the info.

**Comment by aaltat** [comment]
The bug should be fixed in the SeleniumLibrary master branch. Pip supports installation from the GitHub,  please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#installation Could you try fix and see does it resolve your problem?

**Comment by deepakaravind** [comment]
Still facing the issue.  Tried to upgrade using pip install upgrade option and also to be sure created a fresh project with fresh installation.  This is what my pip list shows with with the version of 3.2.0 for seleniumlibrary properly installed
![image](https://user-images.githubusercontent.com/23402701/49654758-b6e4dd00-fa06-11e8-8c11-f61d37936702.png)

On further looking at the code under site-package keywords -> windows.py, I still see the old code and don't see the fix that you have provided.  Not sure if am doing something wrong here.

Here are the debug logs
Traceback (most recent call last):
  File "c:\cgtavenv\lib\site-packages\SeleniumLibrary\__init__.py", line 369, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "c:\cgtavenv\lib\site-packages\SeleniumLibrary\base\robotlibcore.py", line 102, in run_keyword
    return self.keywords[name](*args, **kwargs)
  File "c:\cgtavenv\lib\site-packages\SeleniumLibrary\keywords\window.py", line 149, in get_window_titles
    return self._log_list(titles)
  File "c:\cgtavenv\lib\site-packages\SeleniumLibrary\keywords\window.py", line 226, in _log_list
    msg.append('{}: {}'.format(index + 1, item))

**Comment by deepakaravind** [comment]
Still facing the issue. Tried to upgrade using pip install upgrade option and also to be sure created a fresh project with fresh installation. This is what my pip list shows with with the version of 3.2.0 for seleniumlibrary properly installed
![image](https://user-images.githubusercontent.com/23402701/49655708-5d31e200-fa09-11e8-9e5b-4c95727ef51e.png)
On further looking at the code under site-package keywords -> windows.py, I still see the old code and don't see the fix that you have provided for this specific issue with plural_or_not module. Not sure if am doing something wrong here.
Here are the debug logs
Traceback (most recent call last):
File "c:\cgtavenv\lib\site-packages\SeleniumLibrary_init_.py", line 369, in run_keyword
return DynamicCore.run_keyword(self, name, args, kwargs)
File "c:\cgtavenv\lib\site-packages\SeleniumLibrary\base\robotlibcore.py", line 102, in run_keyword
return self.keywords[name](*args, **kwargs)
File "c:\cgtavenv\lib\site-packages\SeleniumLibrary\keywords\window.py", line 149, in get_window_titles
return self._log_list(titles)
File "c:\cgtavenv\lib\site-packages\SeleniumLibrary\keywords\window.py", line 226, in _log_list
msg.append('{}: {}'.format(index + 1, item))

**Comment by deepakaravind** [comment]
I also saw this bug was tagged to the release 3.3.0?

**Comment by aaltat** [comment]
It seems that you installed the wrong versions, please install with: 
```
pip install -U git+https://github.com/robotframework/SeleniumLibrary.git
```
It will install directly from the GitHub repository master branch. Then retry with the problem. 

The 3.2.0 is already out and can not be changed. The next release is going to be 3.3.0 and will be released somewhere in the future. I do not feel that this bug is severe enough to call hotfix release, in practice 3.2.1 and therefore this is planned to 3.3.0.

**Comment by deepakaravind** [comment]
ah okay gotcha.  The issue is fixed now, ran my tests and worked fine.  Thanks for providing a quick resolution for this issue.
