### ISSUE TITLE
Wait... keywords should not fail StaleElementReferenceException

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1270]
The `Wait ...` keywords can fail to `StaleElementReferenceException` because in between finding the element and doing action with the element (like checking is the element displayed) the DOM may change. Finding the element and doing something with the element are always two different Selenium API calls, even when doing it Python way: `self.find_element(locator).text` and therefore there is always small delay between the calls. 

There are various reasons why the DOM may change, but the `Wait ...` keywords should not fail, in middle of the waiting, if Selenium raises `StaleElementReferenceException`. Change the `Wait ...` keywords to suppress the `StaleElementReferenceException` and log it. 

This issue replaces the #475

**Comment by tminakov** [comment]
Thank you for this; it was about time, strange no one of us the users have complained about it. 

I literally opened the source to see is this fixed in the latest master (I am running 3.2.0) and start creating a PR, and now I have a solid reason to upgrade to 3.3.1 (which fixes some issues I was hitting in my only test with 3.3.0, I'm doing some crazy stuff to reuse a browser).

**Comment by aaltat** [comment]
Thank you for the nice words.

**Comment by hfy1111** [comment]
just read the whole threads.. i did not see any solution except use except StaleElementReferenceException to ignore the issue. 

Since now i am still seeing this every often when running multiple scripts at the same time.

**Comment by emanlove** [comment]
@hfy1111 Do you have any specific situations under which this is occurring? And are you using anyone specific `Wait ...` keyword where this occurs?

**Comment by hfy1111** [comment]
> @hfy1111 Do you have any specific situations under which this is occurring? And are you using anyone specific `Wait ...` keyword where this occurs?
Here is the error message from the report, i was using wait_until_element_is_visible, and it is only happening when running several test cases together at the same time, if run only this case, the error will not come out. 
just wonder, do you have any solution for this? 
thanks!
  
StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=103.0.5060.53)
Stacktrace:
0   chromedriver                        0x000000010326a0f9 chromedriver + 4448505
1   chromedriver                        0x00000001031f5f73 chromedriver + 3972979
2   chromedriver                        0x0000000102e90268 chromedriver + 410216
3   chromedriver                        0x0000000102e93117 chromedriver + 422167
4   chromedriver                        0x0000000102e92fb6 chromedriver + 421814
5   chromedriver                        0x0000000102e93b7d chromedriver + 424829
6   chromedriver                        0x0000000102ef70c3 chromedriver + 831683
7   chromedriver                        0x0000000102ee3a12 chromedriver + 752146
    [ Message content over the limit has been removed. ]
...hromedriver                        0x0000000102ebaca5 chromedriver + 584869
12  chromedriver                        0x000000010323b45d chromedriver + 4256861
13  chromedriver                        0x00000001032403dd chromedriver + 4277213
14  chromedriver                        0x000000010324535f chromedriver + 4297567
15  chromedriver                        0x000000010324103a chromedriver + 4280378
16  chromedriver                        0x000000010321a86f chromedriver + 4122735
17  chromedriver                        0x000000010325b448 chromedriver + 4387912
18  chromedriver                        0x000000010325b5cf chromedriver + 4388303
19  chromedriver                        0x0000000103271545 chromedriver + 4478277
20  libsystem_pthread.dylib             0x00007ff81f3724f4 _pthread_start + 125
21  libsystem_pthread.dylib             0x00007ff81f36e00f thread_start + 15
