### ISSUE TITLE
warnings for some acceptance test

### ISSUE THREAD

**Issue by ghost** [robotframework/SeleniumLibrary#602]
following 2 acceptance testcases produce warning instead of the expected error message:
 Select Non-Existing Item From Single Selection List
 Unselect Non-Existing Item From List 

looks like both testcases need an update 
[ WARN ] Option(s) 'Tin Can Phone' not found within list 'preferred_channel'.
[ WARN ] Option(s) 'Tin Can Phone' not found within list 'preferred_channel'.
[ WARN ] Option(s) 'Smoke Signals' not found within list 'preferred_channel'.
Select Non-Existing Item From Single Selection List :: Select Non-... | PASS |

[ WARN ] Tried to unselect missing selection item, 'Tin Can Phone' from locator 'possible_channels'.
[ WARN ] Tried to unselect missing selection item, 'Smoke Signals' from locator 'possible_channels'.
[ WARN ] Tried to unselect missing selection item, 'Tin Can Phone' from locator 'possible_channels'.
[ WARN ] Tried to unselect missing selection item, 'Smoke Signals' from locator 'possible_channels'.
Unselect Non-Existing Item From List :: LOG 3 Unselecting option(s... | PASS |

seems related to commit https://github.com/SeleniumHQ/selenium/commit/91ed4405abcf4d53e399baa3bb6d06ff5d2dd0e2  ( select_by_index, deselect_by_index )
seems related to pull request #597  ( Fixes `Unselect From List` due to Selenium changes. ) but now for keyword "Select From List"

**Comment by divfor** [comment]
this has been fixed by recently PR merged to master

**Comment by ghost** [comment]
I assume you refer to PR #597, this PR only fixes the failed testcases ( related to Unselect From List ).
This issue refers to the (different) warning messages which are still present (for different testcases)

**Comment by HelioGuilherme66** [comment]
I wrote the warning messages differently on purpose, because they exist in a different context. They are just warning messages. There are no statuscheck (postprocessing) for the messages. Do you think it should?

**Comment by ghost** [comment]
Both testcases specifically check for returned warning messages,  possible solution is to rewrite the testcase such that they expect the new warning message text.
in short the testcase expects warning message "A" but now gets warning message "B" 

I already indicated testcases needs an update, not the code:
 "  looks like both testcases need an update  "

**Comment by HelioGuilherme66** [comment]
The tests are not expecting the Warning messages.
- The _Select Non-Existing Item From Single Selection List_ is a Negative test case, so `Run Keyword And Expect Error`, expects (but without log verification):
  
  > ValueError: Option 'Smoke Signals' not in list 'preferred_channel'.
- The _Unselect Non-Existing Item From List_ expects a log from the 3rd keyword, which is the INFO when starting:
  
  > LOG 3 Unselecting option(s) 'Tin Can Phone, Smoke Signals, Email' from list 'possible_channels'.

I don't think the test cases need updating because there were no changes in the result of tests.

**Comment by ghost** [comment]
ok, then it sounds like there is no problem and this issue should be closed then.

**Comment by HelioGuilherme66** [comment]
Great! (Thanks, for reporting and feedback!)
@pekkaklarck @aaltat @emanlove @zephraph  
I am so happy that an Issue has been Closed in this project! Aren't you also?
